name: Machine Learning CI - Skilled Level

on:
  push:
    branches: [ main ]

jobs:
  train-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install MLflow & Deps
        run: pip install mlflow==2.22.0 pandas scikit-learn

      - name: Run MLflow Project
        run: |
          # Jalanin mlflow run
          mlflow run MLProject/ --env-manager local

      - name: Upload Artifacts
        if: always() # Tetap upload meskipun step sebelumnya error buat debugging
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-data
          path: mlruns/

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image (Advance Point)
        run: |
          # Ambil Run ID terbaru dari hasil training tadi
          LATEST_RUN=$(python -c "import mlflow; print(mlflow.search_runs().iloc[0]['run_id'])")
          
          # Build image pake fungsi mlflow
          mlflow models build-docker \
            -m "runs:/$LATEST_RUN/model" \
            -n "${{ secrets.DOCKERHUB_USERNAME }}/house-price-model:latest" \
            --enable-mlserver

      - name: Push to Docker Hub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/house-price-model:latest